from __future__ import annotations

import copy
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
sys.path.insert(0, str(ROOT))

from yado_evolution_ledger_v2 import validate_ledger_v2, event_hash

V1 = REPO / "candidates/kernel-self-generated/g2-native-main-provenance-rewrite-v1.json"
TARGET_REL = "runtime/yado_unified_core_deep_self_audit_v1.py"
TARGET = REPO / TARGET_REL
HEAD = REPO / "canonical/yado-main-head-g2.json"
CORE = REPO / "canonical/yado-unified-core-v1.json"
LEDGER = REPO / "architecture/evolution-ledger.json"
REGISTRY = REPO / "canonical/yado-unified-experience-registry-v1.json"
GUARD = ROOT / "yado_canonical_invariant_guard_v1.py"
OUT = REPO / "candidates/kernel-self-generated/g2-native-main-provenance-admission-v2.json"
AUDIT_RECEIPT = ROOT / "yado_unified_core_deep_self_audit_v1_receipt.json"


def canon(x: Any) -> str:
    return json.dumps(x, sort_keys=True, separators=(",", ":"), default=str)


def digest(x: Any) -> str:
    return hashlib.sha256(canon(x).encode()).hexdigest()


def fsha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8")


def cdig(obj: dict[str, Any], field: str) -> str:
    x = copy.deepcopy(obj)
    x.pop(field, None)
    return digest(x)


def run_guard(label: str) -> dict[str, Any]:
    cp = subprocess.run([sys.executable, str(GUARD)], cwd=REPO, capture_output=True, text=True, timeout=120)
    if cp.returncode != 0:
        raise RuntimeError(label + ":" + cp.stdout[-5000:] + cp.stderr[-1200:])
    return json.loads(cp.stdout)


v1 = load(V1)
if v1.get("status") != "PASS_SHADOW_G2_NATIVE_MAIN_PROVENANCE_REWRITE_V1":
    raise RuntimeError("V1_PASS_SHADOW_REQUIRED")
if v1.get("external_model_used") is not False or v1.get("native_ast_materialization") is not True:
    raise RuntimeError("V1_NATIVE_ONLY_EVIDENCE_REQUIRED")
if v1.get("target_path") != TARGET_REL:
    raise RuntimeError("V1_TARGET_DRIFT")

candidate_rel = str(v1.get("candidate_path") or "")
CAND = REPO / candidate_rel
if not CAND.exists():
    raise RuntimeError("V1_CANDIDATE_MISSING")
if fsha(CAND) != v1.get("candidate_sha256"):
    raise RuntimeError("V1_CANDIDATE_HASH_DRIFT")

head = load(HEAD)
core = load(CORE)
ledger = load(LEDGER)
validate_ledger_v2(ledger)
parent_sha = fsha(TARGET)
candidate_sha = fsha(CAND)

bound_core_parent = (core.get("deep_self_audit") or {}).get("source_sha256")
bound_head_parent = (head.get("unified_core") or {}).get("deep_self_audit_source_sha256")
if parent_sha != bound_core_parent or parent_sha != bound_head_parent:
    raise RuntimeError(f"PARENT_BINDING_DRIFT:{parent_sha}:{bound_core_parent}:{bound_head_parent}")
if parent_sha != v1.get("target_parent_sha256"):
    raise RuntimeError("V1_PARENT_SOURCE_DRIFT")
if candidate_sha == parent_sha:
    raise RuntimeError("CANDIDATE_EQUALS_PARENT")

# Exact transport of the source bytes generated by the native V1 AST path.
TARGET.write_bytes(CAND.read_bytes())
compile(TARGET.read_text(encoding="utf-8"), str(TARGET), "exec")

if TARGET_REL not in core.get("active_runtime_sources", []):
    raise RuntimeError("TARGET_NOT_ACTIVE_RUNTIME_SOURCE")

core.setdefault("deep_self_audit", {})["source_sha256"] = candidate_sha
core["deep_self_audit"]["implementation_version"] = int(core["deep_self_audit"].get("implementation_version") or 0) + 1
core["deep_self_audit"]["native_provenance_admission_v2"] = {
    "status": "CANONICAL_ACTIVE_PENDING_FULL_GATE",
    "source": "YADO_NATIVE_AST_V1_EXACT_CANDIDATE_BYTES",
    "candidate_source_sha256": candidate_sha,
    "rollback_parent_source_sha256": parent_sha,
    "external_model_used": False,
    "v1_receipt_sha256": v1.get("receipt_sha256"),
}

rim = core.setdefault("runtime_integrity_manifest", {})
rim["sources"] = {rel: fsha(REPO / rel) for rel in core.get("active_runtime_sources", [])}
rim["manifest_digest"] = digest(rim["sources"])
core["core_digest"] = cdig(core, "core_digest")
write(CORE, core)

head.setdefault("unified_core", {})["deep_self_audit_source_sha256"] = candidate_sha
head["unified_core"]["runtime_integrity_manifest_digest"] = rim["manifest_digest"]
head["unified_core"]["core_digest"] = core["core_digest"]
previous_head_digest = head.get("canonical_head_digest")
head["canonical_head_digest"] = cdig(head, "canonical_head_digest")
write(HEAD, head)

# Bind the canonical head transition into the causal ledger before executing the new source.
run_id = str(os.getenv("GITHUB_RUN_ID") or "LOCAL")
provisional = {
    "index": len(ledger["events"]),
    "event_id": f"E{len(ledger['events']) + 1:04d}_G2_NATIVE_MAIN_PROVENANCE_AST_ADMISSION_V2",
    "event_type": "G2_NATIVE_MAIN_PROVENANCE_AST_ADMISSION",
    "status": "PASS_CANONICAL_PENDING_FULL_VERIFICATION",
    "generation": ledger["current_head"],
    "deficit": "LEGACY_EXPERIENCE_SUMMARY_PROVENANCE",
    "effect": f"NATIVE_AST_SOURCE={candidate_sha};ROLLBACK={parent_sha};FULL_GATE_REQUIRED=True",
    "source_path": str(V1.relative_to(REPO)),
    "source_digest": v1.get("receipt_sha256"),
    "run_id": run_id,
    "parent_event_hash": ledger["tail_event_hash"],
    "canonical_mutation": True,
    "canonical_mechanism_mutation": True,
    "architecture_mutation": False,
    "promotion_applied": False,
    "generation_transition": False,
    "previous_head_digest": previous_head_digest,
    "new_head_digest": head["canonical_head_digest"],
}
provisional["event_hash"] = event_hash(provisional)
ledger["events"].append(provisional)
ledger["event_count"] = len(ledger["events"])
ledger["tail_event_hash"] = provisional["event_hash"]
ledger["current_head_digest"] = head["canonical_head_digest"]
ledger["ledger_digest"] = digest({k: v for k, v in ledger.items() if k != "ledger_digest"})
validate_ledger_v2(ledger)
write(LEDGER, ledger)

pre_guard = run_guard("PRE_EXEC_CANONICAL_GUARD_FAILED")

audit = subprocess.run([sys.executable, TARGET_REL], cwd=REPO, capture_output=True, text=True, timeout=240)
receipt = load(AUDIT_RECEIPT) if AUDIT_RECEIPT.exists() else {}
prov_finding = next((x for x in receipt.get("findings", []) if x.get("code") == "LEGACY_EXPERIENCE_SUMMARY_PROVENANCE"), {})
valid_checks = {
    "deep_audit_process_pass": audit.returncode == 0,
    "deep_audit_semantic_pass": receipt.get("status") == "PASS_YADO_UNIFIED_CORE_DEEP_SELF_AUDIT_V1",
    "provenance_finding_closed": prov_finding.get("status") == "PASS",
    "provenance_priority_moved": receipt.get("self_selected_next_step") != "LEGACY_EXPERIENCE_SUMMARY_PROVENANCE",
}

# Fresh fail-closed counterfactual: one legacy record falsely claims semantic equivalence.
with tempfile.TemporaryDirectory(prefix="yado-native-prov-v2-") as td:
    dst = Path(td) / "repo"
    shutil.copytree(REPO, dst, ignore=shutil.ignore_patterns(".git", "__pycache__", "*.pyc", "*.sqlite"))
    rp = dst / REGISTRY.relative_to(REPO)
    reg = load(rp)
    legacy = next(x for x in reg.get("branches", []) if x.get("mode") == "EXPERIENCE_ONLY")
    legacy.setdefault("rederived_evidence", {})["semantic_equivalence_to_host_lessons_claimed"] = True
    write(rp, reg)
    bad = subprocess.run([sys.executable, TARGET_REL], cwd=dst, capture_output=True, text=True, timeout=240)
    brp = dst / AUDIT_RECEIPT.relative_to(REPO)
    bad_receipt = load(brp) if brp.exists() else {}
    bad_finding = next((x for x in bad_receipt.get("findings", []) if x.get("code") == "LEGACY_EXPERIENCE_SUMMARY_PROVENANCE"), {})
    counterfactual_checks = {
        "counterfactual_executed": bad.returncode == 0,
        "semantic_overclaim_fails_closed": bad_finding.get("status") != "PASS",
    }

compileall = subprocess.run([sys.executable, "-m", "compileall", "-q", "runtime"], cwd=REPO, capture_output=True, text=True, timeout=240)
checks = {
    "v1_native_evidence_consumed": True,
    "exact_candidate_bytes_transported": fsha(TARGET) == candidate_sha,
    "external_model_used": False,
    "canonical_generation_unchanged": head.get("generation_id") == "G2_CANDIDATE_TRCG_V1",
    "g3_not_started": head.get("g3_genesis_performed") is False,
    "runtime_compileall_pass": compileall.returncode == 0,
    **valid_checks,
    **counterfactual_checks,
}
passed = all(v is True for k, v in checks.items() if k != "external_model_used") and checks["external_model_used"] is False
if not passed:
    raise RuntimeError("V2_POST_TRANSPORT_WITHHOLD:" + json.dumps(checks, sort_keys=True))

# Deep audit may have appended ledger evidence; re-read before final evidence event.
ledger = load(LEDGER)
validate_ledger_v2(ledger)
report = {
    "schema": "yado.g2.native_main_provenance_admission.v2",
    "status": "PASS_CANONICAL_PENDING_FULL_AUDIT_G2_NATIVE_MAIN_PROVENANCE_ADMISSION_V2",
    "source_v1_receipt_sha256": v1.get("receipt_sha256"),
    "target_path": TARGET_REL,
    "rollback_parent_source_sha256": parent_sha,
    "candidate_source_sha256": candidate_sha,
    "previous_head_digest": previous_head_digest,
    "new_head_digest": head["canonical_head_digest"],
    "deep_audit_receipt_sha256": receipt.get("receipt_sha256"),
    "deep_audit_next_step": receipt.get("self_selected_next_step"),
    "provenance_finding": prov_finding,
    "checks": checks,
    "pre_guard_status": pre_guard.get("status"),
    "canonical_mutation": True,
    "canonical_mechanism_mutation": True,
    "architecture_mutation": False,
    "generation_transition": False,
    "g3_genesis_performed": False,
    "automatic_canonical_promotion": False,
    "claim_boundary": "Exact admission of a bounded YADO-native AST candidate into the canonical deep-self-audit runtime. Full kernel audit and full regression remain mandatory before repository promotion. This is not proof of general source genesis or consciousness.",
}
report["receipt_sha256"] = digest(report)
write(OUT, report)

final_event = {
    "index": len(ledger["events"]),
    "event_id": f"E{len(ledger['events']) + 1:04d}_G2_NATIVE_MAIN_PROVENANCE_AST_V2_VERIFIED",
    "event_type": "G2_NATIVE_MAIN_PROVENANCE_AST_VERIFICATION",
    "status": "PASS_VERIFIED_PENDING_FULL_REPOSITORY_GATE",
    "generation": ledger["current_head"],
    "deficit": "LEGACY_EXPERIENCE_SUMMARY_PROVENANCE",
    "effect": f"PROVENANCE=PASS;NEXT={receipt.get('self_selected_next_step')};CANDIDATE={candidate_sha}",
    "source_path": str(OUT.relative_to(REPO)),
    "source_digest": report["receipt_sha256"],
    "run_id": run_id,
    "parent_event_hash": ledger["tail_event_hash"],
    "canonical_mutation": False,
    "canonical_mechanism_mutation": False,
    "architecture_mutation": False,
    "promotion_applied": False,
    "generation_transition": False,
    "previous_head_digest": head["canonical_head_digest"],
    "new_head_digest": head["canonical_head_digest"],
}
final_event["event_hash"] = event_hash(final_event)
ledger["events"].append(final_event)
ledger["event_count"] = len(ledger["events"])
ledger["tail_event_hash"] = final_event["event_hash"]
ledger["current_head_digest"] = head["canonical_head_digest"]
ledger["ledger_digest"] = digest({k: v for k, v in ledger.items() if k != "ledger_digest"})
validate_ledger_v2(ledger)
write(LEDGER, ledger)

post_guard = run_guard("FINAL_CANONICAL_GUARD_FAILED")
print(json.dumps({
    "status": report["status"],
    "candidate_source_sha256": candidate_sha,
    "provenance_status": prov_finding.get("status"),
    "next_step": receipt.get("self_selected_next_step"),
    "counterfactual_status": bad_finding.get("status"),
    "pre_guard": pre_guard.get("status"),
    "post_guard": post_guard.get("status"),
    "new_head_digest": head["canonical_head_digest"],
    "receipt_sha256": report["receipt_sha256"],
}, indent=2, sort_keys=True))
