"""Static workflow-reference contract marker for YADO V2.

The real experience-conditioned runtime candidate is regenerated by the
V2 workflow. This tracked file exists only so repository-level static
reference auditing can verify that every workflow path resolves.
"""

STATUS = "STATIC_REFERENCE_CONTRACT_ONLY"
CANONICAL_MUTATION = False
GENERATED_AT_RUNTIME = True
