from __future__ import annotations

# Generated by runtime/yado_external_source_evolution_v1.py from external TRAINING cases only.
LEAP_A = 4
LEAP_B = 100
LEAP_C = 400
GRAINS_BASE = 2
GRAINS_OFFSET = -1
SQUARE_A = 1
SQUARE_DIVISOR = 2
SQUARE_POWER = 2
SUM_A = 1
SUM_B = 1
SUM_DIVISOR = 6

def square_of_sum(n):
    return ((n * (n + SQUARE_A)) // SQUARE_DIVISOR) ** SQUARE_POWER

def sum_of_squares(n):
    return n * (n + SUM_A) * (2 * n + SUM_B) // SUM_DIVISOR

def solve(exercise, prop, data):
    if exercise == "leap":
        year = int(data["year"])
        return (year % LEAP_A == 0) and ((year % LEAP_B != 0) or (year % LEAP_C == 0))
    if exercise == "grains":
        square = int(data["square"])
        return GRAINS_BASE ** (square + GRAINS_OFFSET)
    if exercise == "difference-of-squares":
        n = int(data["number"])
        if prop == "squareOfSum":
            return square_of_sum(n)
        if prop == "sumOfSquares":
            return sum_of_squares(n)
        if prop == "differenceOfSquares":
            return square_of_sum(n) - sum_of_squares(n)
        raise KeyError(prop)
    raise KeyError(exercise)
